var order2 = {
  "id": null,
  "errorcode": 4,
  "barcode": "EPOS_1720666714947071",
  "local_id": 1,
  "tableUniqID": 1720666714947071,
  "selectDiscount": 0,
  "table_id": 0,
  "order_type": "COLLECTION",
  "changeAmount": 10,
  "order_channel": "EPOS",
  "order_date": "2024-07-11 08:59:04",
  "requester_type": "PROVIDER",
  "requester_id": 0,
  "requester_uuid": 0,
  "shipping_address_id": 0,
  "requested_delivery_timestamp": "2024-07-11 08:59:04",
  "status": "CLOSED",
  "net_amount": 100,
  "discounted_amount": 0,
  "delivery_charge": 0,
  "payable_amount": 100,
  "payment_type": "EPOS_CASH",
  "payment_id": 0,
  "prescriber_id": 0,
  "branch_id": 0,
  "comment": "",
  "created_at": "2024-07-11T08:59:04.691",
  "updated_at": "2024-07-11T08:59:04.691",
  "order_products": [
    {
      "id": 5688,
      "master_id": 0,
      "parent_id": null,
      "order_id": null,
      "product_id": null,
      "parent_product_id": null,
      "unit": 10,
      "net_amount": 10,
      "discountable_amount": null,
      "comment": null,
      "product": {
        "id": 5688,
        "sort_order": 0,
        "uuid": "72937760-0969-105f-9cff-3d7476586b46",
        "barcode": null,
        "type": "ITEM",
        "short_name": "catfish whole",
        "description": null,
        "status": 1,
        "discountable": 1,
        "creator_id": 2,
        "creator_uuid": "9c4aab77-c6b8-43cb-bcc9-7ab0e2cdc3db",
        "tags": null,
        "property": {
          "platform": null,
          "unit_amount": "0",
          "master": "0",
          "epos_category": null,
          "is_coupon": null,
          "category": "mp-detergent",
          "featured": "0",
          "unit_of_sale": "POUND",
          "discount_type": null,
          "discount_value": null,
          "print_order": "3",
          "print_order_enable": "0",
          "purchase_price": null,
          "tare_weight": "0",
          "total_unit": null,
          "total_unit_price": null,
          "cost_price": null,
          "sale_price_without_tax": null,
          "sale_price_with_tax": null,
          "margin": "0",
          "supplier": null,
          "orderCode": null,
          "sell_on_till": "0",
          "unit_product_type": "STANDARD",
          "unit_of_purchase": "POUND"
        },
        "files": []
      },
      "components": [],
      "priceEditManage": false,
      "priceEditComment": "",
      "property": null,
      "selectSubCategoryKey": "mp-detergent",
      "selectMainCategoryKey": "",
      "offer": null
    }
  ],
  "requester": null,
  "requester_guest": null,
  "shipping_address": {"id": null, "name": null, "type": null, "creator_type": null, "creator_id": null, "status": null, "created_at": null, "updated_at": null, "property": null},
  "waiterInfo": {"firstName": "Admin", "id": 0, "role": "ADMIN", "lastName": "", "phone": "admin", "password": "0000", "orderList": [], "loginTime": "2024-07-11 08:55:55", "logoutTime": "2024-07-11 08:55:55"},
  "order_files": [],
  "prescriber": null,
  "payment": null,
  "cash_entry": [
    {"id": null, "timestamp": "2024-07-11T08:59:04.684", "type": "EPOS_CASH", "order_id": 3, "amount": 20, "comment": null, "created_at": null, "updated_at": null},
    {"id": null, "timestamp": "2024-07-11T08:58:59.014", "type": "EPOS_CARD", "order_id": 3, "amount": 40, "comment": null, "created_at": null, "updated_at": null},
    {"id": null, "timestamp": "2024-07-11T08:58:49.022", "type": "EPOS_CASH", "order_id": 3, "amount": 50, "comment": null, "created_at": null, "updated_at": null},
    {"id": null, "timestamp": "2024-07-11T08:59:41.479", "type": "REFUND", "order_id": null, "amount": 20, "comment": null, "created_at": null, "updated_at": null}
  ],
  "branch": {"id": null, "name": "branch-1", "value": null, "created_at": null, "updated_at": null, "property": null},
  "table": null,
  "property": {"comment": null, "requested_delivery_timestamp_type": "ASAP", "total_value_edit": null, "total_value_edit_note": null},
  "vat": 0,
  "totalvalueEdit": false,
  "totalValueEditcomment": "manager has edited price",
  "isDiscountGivenByAmount": false,
  "isDiscountGivenByUser": false,
  "waiterToEposSend": 1,
  "requestTime": 0,
  "entermanuallyRequestTime": false
};
